version: '3'
services:
  redis_dev:
    image: redis/redis-stack-server:latest
    hostname: redis-dev
    ports:
      - 6379:6379
    #    environment:
    #      REDIS_ARGS: --requirepass configurations
    healthcheck:
      test: [ CMD, redis-cli, ping ]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: api
    volumes:
      - .:/core
    environment:
      - REDIS_URL=redis://redis_dev:6379
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - 80:80
    restart: always
