version: '3'
services:
  redis_dev:
    image: redis/redis-stack-server:latest
    hostname: redis-dev
    ports:
      - 6379:6379
    healthcheck:
      test: [ CMD, redis-cli, ping ]
      interval: 5s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - .:/core
    environment:
      - REDIS_HOSTNAME=${REDIS_HOSTNAME}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_DATABASE=${REDIS_DATABASE}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
      - S3_REGION_NAME=${S3_REGION_NAME}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_PATH_PREFIX=${S3_PATH_PREFIX}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
    ports:
      - 80:80
      - 443:443
    restart: always
